# https://pdm-project.org/en/latest/usage/publish/
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.toml"
      - "**.yaml"
  workflow_dispatch: ~

jobs:
  build-n-push:
    name: upload release to Test PyPI
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/miscbox

    permissions:
      # This permission is needed for private repositories.
      # contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11

      - name: Publish package distributions to PyPI
        run: pdm publish -v --repository testpypi
